
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "CODE_EXPRESSION COMMENTARY GRAMMAR LEX PARAMETER SIGNAL STR_ATRIB TOKEN_ID YACCprog : comandoscomandos : comandos : comando comandos comando : LEXcomando : YACCcomando : codecomando : COMMENTARYcode : PARAMETER '=' CODE_EXPRESSIONcode : TOKEN_ID  extra CODE_EXPRESSIONextra : extra : STR_ATRIB extraextra : SIGNAL extracode : GRAMMAR CODE_EXPRESSIONcode : CODE_EXPRESSION"
    
_lr_action_items = {'$end':([0,1,2,3,4,5,6,7,9,12,17,18,19,],[-2,0,-1,-2,-4,-5,-6,-7,-14,-3,-13,-8,-9,]),'LEX':([0,3,4,5,6,7,9,17,18,19,],[4,4,-4,-5,-6,-7,-14,-13,-8,-9,]),'YACC':([0,3,4,5,6,7,9,17,18,19,],[5,5,-4,-5,-6,-7,-14,-13,-8,-9,]),'COMMENTARY':([0,3,4,5,6,7,9,17,18,19,],[7,7,-4,-5,-6,-7,-14,-13,-8,-9,]),'PARAMETER':([0,3,4,5,6,7,9,17,18,19,],[8,8,-4,-5,-6,-7,-14,-13,-8,-9,]),'TOKEN_ID':([0,3,4,5,6,7,9,17,18,19,],[10,10,-4,-5,-6,-7,-14,-13,-8,-9,]),'GRAMMAR':([0,3,4,5,6,7,9,17,18,19,],[11,11,-4,-5,-6,-7,-14,-13,-8,-9,]),'CODE_EXPRESSION':([0,3,4,5,6,7,9,10,11,13,14,15,16,17,18,19,20,21,],[9,9,-4,-5,-6,-7,-14,-10,17,18,19,-10,-10,-13,-8,-9,-11,-12,]),'=':([8,],[13,]),'STR_ATRIB':([10,15,16,],[15,15,15,]),'SIGNAL':([10,15,16,],[16,16,16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prog':([0,],[1,]),'comandos':([0,3,],[2,12,]),'comando':([0,3,],[3,3,]),'code':([0,3,],[6,6,]),'extra':([10,15,16,],[14,20,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> comandos','prog',1,'p_prog','yacc.py',17),
  ('comandos -> <empty>','comandos',0,'p_comandos_varios01','yacc.py',20),
  ('comandos -> comando comandos','comandos',2,'p_comandos_varios02','yacc.py',23),
  ('comando -> LEX','comando',1,'p_comando01','yacc.py',26),
  ('comando -> YACC','comando',1,'p_comando02','yacc.py',37),
  ('comando -> code','comando',1,'p_comando03','yacc.py',42),
  ('comando -> COMMENTARY','comando',1,'p_comando04','yacc.py',46),
  ('code -> PARAMETER = CODE_EXPRESSION','code',3,'p_atrib02','yacc.py',51),
  ('code -> TOKEN_ID extra CODE_EXPRESSION','code',3,'p_atrib06','yacc.py',59),
  ('extra -> <empty>','extra',0,'p_atrib_extra01','yacc.py',83),
  ('extra -> STR_ATRIB extra','extra',2,'p_atrib_extra02','yacc.py',87),
  ('extra -> SIGNAL extra','extra',2,'p_atrib_extra03','yacc.py',91),
  ('code -> GRAMMAR CODE_EXPRESSION','code',2,'p_atrib07','yacc.py',99),
  ('code -> CODE_EXPRESSION','code',1,'p_atrib08','yacc.py',132),
]
